/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cs_ia;

/**
 *
 * @author Rony
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */

    String username;

    public HomePage() {
        initComponents();
        All_Entries.extractDetailsFromDatabaseCSV();
        All_Student_Meetings.readMeetingEventsFile();

    }

    public HomePage(String u) {
        initComponents();
        this.username = u;
        usernameLBL.setText("Hello, " + this.username + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usernameLBL = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jNewEntryButton = new javax.swing.JButton();
        jLoginButton2 = new javax.swing.JButton();
        jLoginButton3 = new javax.swing.JButton();
        jLoginButton4 = new javax.swing.JButton();
        SignOutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        usernameLBL.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        usernameLBL.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Please select an option below to contunue");

        jNewEntryButton.setBackground(new java.awt.Color(255, 255, 255));
        jNewEntryButton.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jNewEntryButton.setForeground(new java.awt.Color(0, 0, 0));
        jNewEntryButton.setText("New Entry");
        jNewEntryButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jNewEntryButton.setContentAreaFilled(false);
        jNewEntryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jNewEntryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewEntryButtonActionPerformed(evt);
            }
        });

        jLoginButton2.setBackground(new java.awt.Color(255, 255, 255));
        jLoginButton2.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLoginButton2.setForeground(new java.awt.Color(0, 0, 0));
        jLoginButton2.setText("Email Generator");
        jLoginButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLoginButton2.setContentAreaFilled(false);
        jLoginButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLoginButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton2ActionPerformed(evt);
            }
        });

        jLoginButton3.setBackground(new java.awt.Color(255, 255, 255));
        jLoginButton3.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLoginButton3.setForeground(new java.awt.Color(0, 0, 0));
        jLoginButton3.setText("Saved Entries");
        jLoginButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLoginButton3.setContentAreaFilled(false);
        jLoginButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLoginButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton3ActionPerformed(evt);
            }
        });

        jLoginButton4.setBackground(new java.awt.Color(255, 255, 255));
        jLoginButton4.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLoginButton4.setForeground(new java.awt.Color(0, 0, 0));
        jLoginButton4.setText("Meeting Scheduler");
        jLoginButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLoginButton4.setContentAreaFilled(false);
        jLoginButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLoginButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton4ActionPerformed(evt);
            }
        });

        SignOutButton.setBackground(new java.awt.Color(255, 0, 51));
        SignOutButton.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        SignOutButton.setForeground(new java.awt.Color(255, 255, 255));
        SignOutButton.setText("Sign out");
        SignOutButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SignOutButton.setBorderPainted(false);
        SignOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(38, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                .createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLoginButton4,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 219,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLoginButton3,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 219,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jNewEntryButton,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 219,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLoginButton2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 219,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(186, 186, 186))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                .createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(usernameLBL,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 548,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                291, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(24, 24, 24))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                .createSequentialGroup()
                                                .addComponent(SignOutButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(24, 24, 24)))));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(usernameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(jNewEntryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLoginButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLoginButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLoginButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27,
                                        Short.MAX_VALUE)
                                .addComponent(SignOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNewEntryButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jNewEntryButtonActionPerformed
        EntryPage e = new EntryPage();
        this.dispose();
        e.setLocationRelativeTo(null);
        e.setVisible(true);
    }// GEN-LAST:event_jNewEntryButtonActionPerformed

    private void jLoginButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jLoginButton2ActionPerformed
        EmailPage m = new EmailPage();
        this.dispose();
        m.setLocationRelativeTo(null);
        m.setVisible(true);
    }// GEN-LAST:event_jLoginButton2ActionPerformed

    private void jLoginButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jLoginButton3ActionPerformed
        SavedEntriesIndividualPage p = new SavedEntriesIndividualPage();
        this.dispose();
        p.setLocationRelativeTo(null);
        p.setVisible(true);
    }// GEN-LAST:event_jLoginButton3ActionPerformed

    private void jLoginButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jLoginButton4ActionPerformed
        MeetingSchedulePage mp = new MeetingSchedulePage();
        this.dispose();
        mp.setLocationRelativeTo(null);
        mp.setVisible(true);
    }// GEN-LAST:event_jLoginButton4ActionPerformed

    private void SignOutButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SignOutButtonActionPerformed
        LoginPage l = new LoginPage();
        l.setLocationRelativeTo(null);
        this.dispose();
        l.setVisible(true);
    }// GEN-LAST:event_SignOutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignOutButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jLoginButton2;
    private javax.swing.JButton jLoginButton3;
    private javax.swing.JButton jLoginButton4;
    private javax.swing.JButton jNewEntryButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel usernameLBL;
    // End of variables declaration//GEN-END:variables
}
