/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cs_ia;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Rony
 */
public class SavedEntriesIndividualPageBroken extends javax.swing.JFrame {

        /**
         * Creates new form SavedEntriesIndividualPage
         */
        public SavedEntriesIndividualPageBroken() {
                initComponents();
                DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
                String[] StudentNames = All_Entries.extractNames();
                for (int i = 0; i < StudentNames.length; i++) {
                        dcbm.addElement(StudentNames[i]);
                }

                StudentNameComboBox.setModel(dcbm);

                int SelectedIndex = StudentNameComboBox.getSelectedIndex();
                Entry SelectedEntry = All_Entries.getAllEntries().get(SelectedIndex);
                SubjectField.setText(SelectedEntry.getSubject());
                rqField.setText(SelectedEntry.getRq());
                DescField.setText(SelectedEntry.getDescription());
                TopicField.setText(SelectedEntry.getTopic());
                Priority.setSelectedItem(SelectedEntry.getPriorityText());
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                StudentNameComboBox = new javax.swing.JComboBox<>();
                SubjectField = new javax.swing.JTextField();
                jTextField4 = new javax.swing.JTextField();
                rqField = new javax.swing.JTextField();
                TopicField = new javax.swing.JTextField();
                jLoginButton2 = new javax.swing.JButton();
                jLoginButton3 = new javax.swing.JButton();
                jLoginButton4 = new javax.swing.JButton();
                jLoginButton5 = new javax.swing.JButton();
                Priority = new javax.swing.JComboBox<>();
                jLabel3 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                DescField = new javax.swing.JTextArea();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));

                jLabel1.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(0, 0, 0));
                jLabel1.setText("View Saved Entries");

                jLabel2.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(0, 0, 0));
                jLabel2.setText("Priority:");

                StudentNameComboBox.setBackground(new java.awt.Color(255, 255, 255));
                StudentNameComboBox.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
                StudentNameComboBox.setForeground(new java.awt.Color(0, 0, 0));
                StudentNameComboBox.setModel(
                                new javax.swing.DefaultComboBoxModel<>(new String[] { "Student 1", "Student 2" }));
                StudentNameComboBox.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                StudentNameComboBoxActionPerformed(evt);
                        }
                });

                SubjectField.setBackground(new java.awt.Color(255, 255, 255));
                SubjectField.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
                SubjectField.setForeground(new java.awt.Color(0, 0, 0));
                SubjectField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                SubjectField.setText("Subject");
                SubjectField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

                jTextField4.setBackground(new java.awt.Color(255, 255, 255));
                jTextField4.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
                jTextField4.setForeground(new java.awt.Color(0, 0, 0));
                jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField4.setText("Meeting Time");
                jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

                rqField.setBackground(new java.awt.Color(255, 255, 255));
                rqField.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
                rqField.setForeground(new java.awt.Color(0, 0, 0));
                rqField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                rqField.setText("Research Question");
                rqField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

                TopicField.setBackground(new java.awt.Color(255, 255, 255));
                TopicField.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
                TopicField.setForeground(new java.awt.Color(0, 0, 0));
                TopicField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                TopicField.setText("Topic");
                TopicField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

                jLoginButton2.setBackground(new java.awt.Color(226, 226, 226));
                jLoginButton2.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
                jLoginButton2.setForeground(new java.awt.Color(0, 0, 0));
                jLoginButton2.setText("Table");
                jLoginButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
                jLoginButton2.setContentAreaFilled(false);
                jLoginButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                jLoginButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jLoginButton2ActionPerformed(evt);
                        }
                });

                jLoginButton3.setBackground(new java.awt.Color(226, 226, 226));
                jLoginButton3.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
                jLoginButton3.setForeground(new java.awt.Color(0, 0, 0));
                jLoginButton3.setText("Update");
                jLoginButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
                jLoginButton3.setContentAreaFilled(false);
                jLoginButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                jLoginButton4.setBackground(new java.awt.Color(226, 226, 226));
                jLoginButton4.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
                jLoginButton4.setForeground(new java.awt.Color(0, 0, 0));
                jLoginButton4.setText("Create New");
                jLoginButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
                jLoginButton4.setContentAreaFilled(false);
                jLoginButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                jLoginButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jLoginButton4ActionPerformed(evt);
                        }
                });

                jLoginButton5.setBackground(new java.awt.Color(226, 226, 226));
                jLoginButton5.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
                jLoginButton5.setForeground(new java.awt.Color(0, 0, 0));
                jLoginButton5.setText("Update");
                jLoginButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
                jLoginButton5.setContentAreaFilled(false);
                jLoginButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                jLoginButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jLoginButton5ActionPerformed(evt);
                        }
                });

                Priority.setBackground(new java.awt.Color(255, 255, 255));
                Priority.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
                Priority.setForeground(new java.awt.Color(0, 0, 0));
                Priority.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "High" }));

                jLabel3.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(0, 0, 0));
                jLabel3.setText("Select a student to view all the details");

                DescField.setBackground(new java.awt.Color(255, 255, 255));
                DescField.setColumns(20);
                DescField.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
                DescField.setForeground(new java.awt.Color(0, 0, 0));
                DescField.setLineWrap(true);
                DescField.setRows(5);
                DescField.setText("Description / Notes");
                DescField.setWrapStyleWord(true);
                DescField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jScrollPane1.setViewportView(DescField);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jLabel1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                383,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                false)
                                                                                                                                                .addComponent(SubjectField)
                                                                                                                                                .addComponent(rqField)
                                                                                                                                                .addComponent(jScrollPane1))
                                                                                                                                .addGap(112, 112,
                                                                                                                                                112)
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(jLoginButton3,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                147,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(jLoginButton2,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                147,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(jLoginButton4,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                147,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                                .addComponent(jLoginButton5,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                147,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                                                false)
                                                                                                                                                                                .addComponent(jTextField4,
                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                215,
                                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                                .addComponent(TopicField))))))
                                                                                                .addContainerGap(72,
                                                                                                                Short.MAX_VALUE))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(StudentNameComboBox,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                99,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                123,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jLabel2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                57,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(3, 3, 3)
                                                                                                .addComponent(Priority,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                99,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(283, 283, 283))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel3,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                516,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(0, 0, Short.MAX_VALUE)))));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                35,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel3)
                                                                .addGap(12, 12, 12)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(StudentNameComboBox,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLoginButton5,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                36,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(Priority,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel2))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(SubjectField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                36,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(TopicField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                36,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(rqField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                36,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jTextField4,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                36,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLoginButton3,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                36,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jLoginButton4,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                36,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(13, 13, 13)
                                                                                                .addComponent(jLoginButton2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                36,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(jScrollPane1))
                                                                .addContainerGap(22, Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>

        private void jLoginButton2ActionPerformed(java.awt.event.ActionEvent evt) {
                SavedEntriesTablePage j = new SavedEntriesTablePage();
                this.dispose();
                j.setLocationRelativeTo(null);
                j.setVisible(true);
                
        }

        private void jLoginButton4ActionPerformed(java.awt.event.ActionEvent evt) {
                EntryPage e = new EntryPage();
                this.dispose();
                e.setLocationRelativeTo(null);
                e.setVisible(true);
        }

        private void jLoginButton5ActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
        }

        private void StudentNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
                int SelectedIndex = StudentNameComboBox.getSelectedIndex();
                Entry SelectedEntry = All_Entries.getAllEntries().get(SelectedIndex);
                SubjectField.setText(SelectedEntry.getSubject());
                rqField.setText(SelectedEntry.getRq());
                DescField.setText(SelectedEntry.getDescription());
                TopicField.setText(SelectedEntry.getTopic());
                Priority.setSelectedItem(SelectedEntry.getPriorityText());
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(SavedEntriesIndividualPageBroken.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(SavedEntriesIndividualPageBroken.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(SavedEntriesIndividualPageBroken.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(SavedEntriesIndividualPageBroken.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new SavedEntriesIndividualPageBroken().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify
        private javax.swing.JTextArea DescField;
        private javax.swing.JComboBox<String> Priority;
        private javax.swing.JComboBox<String> StudentNameComboBox;
        private javax.swing.JTextField SubjectField;
        private javax.swing.JTextField TopicField;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JButton jLoginButton2;
        private javax.swing.JButton jLoginButton3;
        private javax.swing.JButton jLoginButton4;
        private javax.swing.JButton jLoginButton5;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextField jTextField4;
        private javax.swing.JTextField rqField;
        // End of variables declaration
}
